
name: Release on Tag

on:
  push:
    tags:
      - "v*"  # Triggers only when a version tag (vX.X.X) is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Project
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

