
name: Release Rust Project

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build Executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish Artifacts and Release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: my-rust-app  # Change to your binary name
          target: ${{ matrix.platform.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            target/${{ matrix.platform.target }}/release/*
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.platform.target }}/release/*
          tag_name: v1.0.${{ github.run_number }}  # Change to fit your versioning style
          body_path: Changes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

