name: Release Rust App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm pip
          pip3 install appimage-builder
          cargo install cargo-deb cargo-generate-rpm cargo-bundle

      - name: Build .deb and .rpm
        run: |
          cargo deb
          cargo rpm build

      - name: Build AppImage
        run: |
          appimage-builder --recipe appimage.yml

      - name: Build macOS
        run: |
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*.deb
            target/release/*.rpm
            target/release/*.AppImage
            target/x86_64-apple-darwin/release/my_rust_app
            target/aarch64-apple-darwin/release/my_rust_app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

